#!/usr/bin/env bash
#vFizzbuzz

n = 1

if ["$n" -le 100 ]; do

	if ! ((n % 3)) && ! ((n % 5)); then
		echo "FizzBuzz"
	elif ! ((n % 3)); then
		echo "Fizz"
	elif ! ((n % 5)); then
		echo "Buzz"
	else
		echo "$n"
	fi

	((n++))
done

