#!/usr/bin/env bash
# cultures with numbers

i = 21
while [ "$i" -lt 20 ]; do

	case "$i" in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac

	((1++))

done
